name: Use Private Action from Another Repo

on: [workflow_dispatch]

jobs:
  run-private-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm ci 
      
      - name: Execute Private Action from repository 04_practice_project_problem
        uses: ./.github/actions/my-private-action
      
      - name: Run tests
        run: npm test

      - name: Checkout private action from another repository
        uses: actions/checkout@v4
        with:
          repository: 'andreeanatalia/04_practice_project_problem'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: '.github/actions/my-private-action'

      - name: Execute Private Action from repository 04_practice_project_problem
        uses: ./.github/actions/my-private-action